apiVersion: v1
kind: Service
metadata:
  name: myapp1-loadbalancer
  labels: 
    app: myapp1
spec:
  type: NodePort 
  selector:
    app: myapp1
  ports: 
    - port: 80
      targetPort: 80
      nodePort: 30062
